name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build
        run: |
          yarn set version berry
          yarn install --immutable
          yarn run build
          tar czf build.tgz node_modules lib
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build.tgz

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Get build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: Extract build artifacts
        run: tar xzf build.tgz
      - name: Use yarn berry
        run: yarn set version berry
      - name: Publish
        run: yarn npm publish
        env:
          YARN_NPM_PUBLISH_REGISTRY: https://registry.npmjs.org/
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
      - name: Get build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: Extract build artifacts
        run: tar xzf build.tgz
      - name: Use yarn berry
        run: yarn set version berry
      - name: Publish
        run: yarn npm publish
        env:
          YARN_NPM_PUBLISH_REGISTRY: https://npm.pkg.github.com/
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
